//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futebol
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clube
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clube()
        {
            this.Treinador = new HashSet<Treinador>();
            this.Jogadores = new HashSet<Jogadores>();
        }
    
        public int IDClube { get; set; }
        public int IDEstadio { get; set; }

        [Required(ErrorMessage = "O campo nome é de preenchimento obrigatório")]
        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza o nome corretamente")]
        [MaxLength(50)]
        public string Nome { get; set; }

        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza o nome do presidente corretamente")]
        [MaxLength(50)]
        public string Presidente { get; set; }

        [MaxLength(100)]
        public string Morada { get; set; }

        [DataType(DataType.PostalCode)]
        [RegularExpression(@"\d{4}([\-]\d{3})?", ErrorMessage = "Introduza o código postal corretamente")]
        public string CodigoPostal { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Introduza o Telefone corretamente")]
        public int Telefone { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        [MaxLength(50)]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treinador> Treinador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jogadores> Jogadores { get; set; }
        public virtual Estadio Estadio { get; set; }
    }
}
