//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futebol
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Estadio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estadio()
        {
            this.Clube = new HashSet<Clube>();
        }
    
        public int IDEstadio { get; set; }

        [Required(ErrorMessage = "O campo nome é de preenchimento obrigatório")]
        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza o nome corretamente")]
        [MaxLength(50)]
        public string Nome { get; set; }

        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza a localização corretamente")]
        [MaxLength(50)]
        public string Localizacao { get; set; }

        [RegularExpression(@"^[0-9,.]+$", ErrorMessage = "Introduza a capacidade do estádio corretamente")]  
        [MaxLength(7)]
        public string Capacidade { get; set; }

        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza o arquiteto corretamente")]
        [MaxLength(50)]
        public string Arquiteto { get; set; }

        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Data Inválida")]
        public Nullable<System.DateTime> Inauguracao { get; set; }

        [RegularExpression(@"^[0-9,.]+$", ErrorMessage = "Introduza o custo de construção do estádio corretamente")]
        [MaxLength(12)]
        public string CustoConstrucao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clube> Clube { get; set; }
    }
}
