//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futebol
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Jogadores
    {
        public int IDJogador { get; set; }
        public int IDClube { get; set; }
        public int IDAgente { get; set; }
        public int IDPosicao { get; set; }

        [Required(ErrorMessage = "O campo nome é de preenchimento obrigatório")]
        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza o nome corretamente")]
        [MaxLength(50)]
        public string Nome { get; set; }

        public Nullable<int> Numero { get; set; }

        [RegularExpression(@"^[0-9,.]+$", ErrorMessage = "Introduza a altura corretamente")]
        [MaxLength(5)]
        public string Altura { get; set; }

        [RegularExpression(@"^[0-9,.]+$", ErrorMessage = "Introduza o peso corretamente")]
        [MaxLength(5)]
        public string Peso { get; set; }

        [Required(ErrorMessage = "A data de nascimento é de preenchimento obrigatório")]
        [DataType(DataType.Date, ErrorMessage = "Data Inválida")]
        public System.DateTime DataNascimento { get; set; }
        public Nullable<int> Idade { get; set; }
    
        public virtual Agente Agente { get; set; }
        public virtual Clube Clube { get; set; }
        public virtual Posicao Posicao { get; set; }
    }
}
