//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futebol
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Treinador
    {
        public int IDTreinador { get; set; }
        public int IDAgente { get; set; }
        public int IDClube { get; set; }

        [Required(ErrorMessage = "O campo nome é de preenchimento obrigatório")]
        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza o nome corretamente")]
        [MaxLength(50)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo idade é de preenchimento obrigatório")]
        public int Idade { get; set; }

        [Required(ErrorMessage = "O campo nacionalidade é de preenchimento obrigatório")]
        [RegularExpression(@"^[a-z^à-ú A-ZÀ-ú]+$", ErrorMessage = "Introduza a nacionalidade corretamente")]
        [MaxLength(50)]
        public string Nacionalidade { get; set; }
    
        public virtual Agente Agente { get; set; }
        public virtual Clube Clube { get; set; }
    }
}
